name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install build-essential openssl pkg-config libssl-dev libncurses5-dev pkg-config minizip libelf-dev flex bison  libc6-dev libidn11-dev rsync bc liblz4-tool gcc-aarch64-linux-gnu dpkg-dev dpkg git
        wget https://github.com/qqdasb/my-files/raw/master/linux-rk35xx-legacy.config
        git clone https://github.com/armbian/linux-rockchip/
        mv linux-rk35xx-legacy.config linux-rockchip/.config
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
