name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install build-essential openssl pkg-config libssl-dev libncurses5-dev pkg-config minizip libelf-dev flex bison  libc6-dev libidn11-dev rsync bc liblz4-tool gcc-aarch64-linux-gnu gcc u-boot-tools dpkg-dev dpkg git python3-pip qemu-user-static
        sudo pip install elftools --break-system-packages
        wget https://raw.githubusercontent.com/qqdasb/my-files/master/linux-rk35xx-legacy.config
        git clone https://github.com/armbian/linux-rockchip.git --depth 1
        mv linux-rk35xx-legacy.config linux-rockchip/.config
        git clone https://github.com/w568w/u-boot-orangepi-3b --recursive
        wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
        sudo dd if=/dev/zero of=archlinux.img bs=3G count=6
        sudo mkfs.ext4 archlinux.img
        mkdir arch
        sudo tar xvf ArchLinuxARM-aarch64-latest.tar.gz -C arch
        sudo cp -b /etc/resolv.conf arch/etc/resolv.conf
        sudo cp /usr/bin/qemu-aarch64-static arch/usr/bin/
        sudo mount --bind /dev arch/dev
        sudo mount -t devpts devpts arch/dev/pts -o gid=5,mode=620
        sudo mount -t proc proc arch/proc
        sudo mount -t sysfs sysfs arch/sys
        sudo mount -t tmpfs tmpfs arch/run
        sudo mount --bind arch arch
    - name: Build Kernel
      run: |
        cd linux-rockchip
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
        cd ..
        mv linux-rockchip arch/linux
    - name: Build U-boot
      run: |
        cd /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/u-boot-orangepi-3b
        chmod +x orangepi-3b-build.sh
        ./orangepi-3b-build.sh
        cp u-boot-rockchip.bin /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/
        cd /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/
    - name: Build Rootfs
      run: |
        sudo chroot arch pacman-key --init
        sudo chroot arch pacman-key --populate
        sudo chroot arch pacman -Syyu --noconfirm
        sudo chroot arch pacman -S --noconfirm base-devel make git networkmanager
        sudo chroot arch pacman -R --noconfirm linux-arm64 linux-firmware
        sudo chroot arch git clone https://github.com/armbian/firmware.git --depth 1
        sudo chroot arch mv firmware /usr/lib/
        sudo chroot arch ldconfig
        sudo chroot arch make linux/ INSTALL_MOD_PATH=/usr modules_install
        sudo chroot arch make linux/ dtbs_install
        sudo chroot arch make linux/ INSTALL_HDR_PATH=/ headers_install
        sudo chroot arch ls /usr/lib/modules && ls /boot
        sudo chroot arch mkinitcpio --generate /boot/initrd.img- --kernel 
        sudo umount ~/workspace/arch/run
        sudo umount arch/sys
        sudo umount arch/proc
        sudo umount arch/dev/pts
        sudo umount arch/dev
    - name: Build image
      run: |
        mkdir rootfs
        sudo mount archlinux.img rootfs/
        sudo cp -rfp arch/*  rootfs/
        sudo umount rootfs/
        sudo e2fsck -p -f archlinux.img
        sudo resize2fs -M archlinux.img
        sudo dd if=u-boot-rockchip.bin of=/home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/archlinux.img seek=64
    - uses: actions/upload-artifact@v3
      with:
        name: ArchLinuxArm-OrangePi3B
        path: /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/archlinux.img
