name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install build-essential openssl pkg-config libssl-dev libncurses5-dev pkg-config minizip libelf-dev flex bison  libc6-dev libidn11-dev rsync bc liblz4-tool gcc-aarch64-linux-gnu dpkg-dev dpkg git qemu-user-static
        wget https://github.com/qqdasb/my-files/raw/master/linux-rk35xx-legacy.config
        git clone https://github.com/armbian/linux-rockchip/
        mv linux-rk35xx-legacy.config linux-rockchip/.config
        wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
        dd if=/dev/zero of=archlinux.img bs=3G count=6
        mkfs.ext4 archlinux.img
        mkdir arch
        tar xvf ArchLinuxARM-aarch64-latest.tar.gz -C arch
        sudo cp /etc/resolv.conf arch/etc/resolv.conf
        sudo mount --bind /dev arch/dev
        sudo mount -t devpts devpts arch/dev/pts -o gid=5,mode=620
        sudo mount -t proc proc arch/proc
        sudo mount -t sysfs sysfs arch/sys
        sudo mount -t tmpfs tmpfs arch/run
    - name: Build Kernel
      run: |
        cd linux-rockchip
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
