name: Build Armbian

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh BOARD=orangepi3b BRANCH=edge RELEASE=sid BUILD_ONLY= KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BUILD_DESKTOP=no EXTERNAL=yes INSTALL_HEADERS=yes EXTERNAL_NEW=compile
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-Opi3b-Debian-sid-edge
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/Armbian-unofficial_24.8.0-trunk_Orangepi3b_sid_legacy_5.10.160_minimal.img
