name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install arch-install-scripts build-essential openssl pkg-config libssl-dev libncurses5-dev pkg-config minizip libelf-dev flex bison  libc6-dev libidn11-dev rsync bc liblz4-tool gcc-aarch64-linux-gnu gcc u-boot-tools dpkg-dev dpkg git python3-pip qemu-user-static
        sudo pip install pyelftools
        wget https://raw.githubusercontent.com/qqdasb/my-files/master/linux-rk35xx-legacy.config
        git clone https://github.com/armbian/linux-rockchip.git --depth 1
        mv linux-rk35xx-legacy.config linux-rockchip/.config
        git clone https://github.com/w568w/u-boot-orangepi-3b --recursive
        wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
        sudo dd if=/dev/zero of=archlinux.img bs=3G count=6
        sudo mkfs.ext4 archlinux.img
        mkdir arch
        sudo mount archlinux.img arch
        sudo tar xvf ArchLinuxARM-aarch64-latest.tar.gz -C arch
        sudo cp /usr/bin/qemu-aarch64-static arch/usr/bin/
    - name: Build Kernel
      run: |
        cd linux-rockchip
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
        cd ..
        sudo mv linux-rockchip arch/linux
    - name: Build U-boot
      run: |
        cd /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/u-boot-orangepi-3b
        chmod +x orangepi-3b-build.sh
        sudo ./orangepi-3b-build.sh
        cp u-boot-rockchip.bin /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/
        cd /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/
    - name: Build Rootfs
      run: |
        sudo arch-chroot arch pacman-key --init
        sudo arch-chroot arch pacman-key --populate
        sudo arch-chroot arch pacman -Syyu --noconfirm
        sudo arch-chroot arch pacman -S --noconfirm base-devel make git networkmanager
        sudo arch-chroot arch pacman -R --noconfirm linux-arm64 linux-firmware
        sudo arch-chroot arch git clone https://github.com/armbian/firmware.git --depth 1
        sudo arch-chroot arch mv firmware /usr/lib/
        sudo arch-chroot arch ldconfig
        sudo arch-chroot arch make linux/ INSTALL_MOD_PATH=/usr modules_install
        sudo arch-chroot arch make linux/ dtbs_install
        sudo arch-chroot arch make linux/ INSTALL_HDR_PATH=/ headers_install
        sudo arch-chroot arch ls /usr/lib/modules && ls /boot
        sudo arch-chroot arch mkinitcpio --generate /boot/initrd.img- --kernel 
    - name: Build Image
      run: |
        sudo umount arch
        sudo e2fsck -p -f archlinux.img
        sudo resize2fs -M archlinux.img
        sudo dd if=/home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/u-boot-rockchip.bin of=/home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/archlinux.img seek=64
    - uses: actions/upload-artifact@v4
      with:
        name: ArchLinuxArm-OrangePi3B
        path: /home/runner/work/build-archlinuxarm-opi3b/build-archlinuxarm-opi3b/archlinux.img
