name: Build Kernel Nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        git clone https://github.com/armbian/linux-rockchip.git
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
        qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
        debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
        udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
        python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
        python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools
    - name: Download Config
      run: 
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
